/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ResultInterface */

#ifndef _Included_ResultInterface
#define _Included_ResultInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ResultInterface
 * Method:    init
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_ResultInterface_init
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     ResultInterface
 * Method:    countMines
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ResultInterface_countMines
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
